### ISSUE TITLE
All events since last refresh not coming though, only the last one

### ISSUE THREAD

**Issue by eulogious** [dknowles2/pyschlage#116]
After integration refresh, not all events come through to home assistant, only the last one.  This proves to be problematic.  

Scenario:  I come home, put in my code to unlock the door, go inside house, and immediately lock the door.  HA will only see the locked thumbturn event, not the unlock event that happened before it.  I use the unlock event to trigger other things in HA for location based info and it is really nice to que off of the unlock event to set someone home, etc.  Not seeing all the events that happened during the refresh period of the lock integration makes some of these automations not usable anymore.  All the events are in the history of the schlage app.

Is it possible to get all the events that happened between integration refreshes, not just the last one in the history?  Or am I missing something?

Thank you!

**Comment by dknowles2** [comment]
I don't see a way to inject things into the HA logbook. Entries end up there when the state inside HA changes. The Schlage API keeps its own set of logs, which we have access to, but AFAIK there's no place to surface them in HA.

**Comment by eulogious** [comment]
Thank you for the reply!

I should clarify and say that I don’t care about when the events come in, just that they come in.  Something like the integration “caches” the missed events it finds since the last refresh and then fires them one after the other.  Even if the event comes in late to ha, that would be fine as long as the event comes in.  

I am not sure that it’s possible, but that would avoid having to right to HA logbook directly.  Or something?  

Thanks again!

**Comment by dknowles2** [comment]
I don't think that would work. You can't really fire events like that in HA, and even if you could, I'm pretty sure the HA maintainers would reject it.

**Comment by eulogious** [comment]
So there is really no way to grab the missed events?  That seems silly.  It’s a simple thing to do since all the info needed is exposed via an api.  Seems like there is something missing here.  If it’s available in the api, available from the app, there should be no reason all the events aren’t available in home assistant.  Seems like there is a big missing piece here not being able to grab all the events from the api that are available.

I doubt the HA designers and maintainers designed a system where all events during a refresh would not be able to be grabbed from an api.  Seems like a big thing to miss at this point in the game.

Why did you close this?  Are you not willing to figure out how to grab events from the api at all?  Is my request asking too much?  Didn’t think asking for what’s available in the api to be available in HA would be too much of an ask…. If so, it is what it is I guess :-|

Thanks again!

**Comment by dknowles2** [comment]
The HA logbook is only populated by events that are triggered by a state change observed by HA itself. It doesn't understand how to import events that happen outside of its purview. You might be able to hack around this by faking all the changes as you suggested, but I don't think the HA maintainers would allow that through code review. Feel free to re-open this request as an HA issue, but from my perspective this is infeasible.
